//! ckb-testtool accept/reject proof for the Phase-4 escrow-lock COURT path (tag=1).
//!
//! The escrow cell holds the pot. Its lock is the `escrow-lock` script with
//! `args = player0_id(20) ‖ player1_id(20) ‖ nonce0_commit(32) ‖ nonce1_commit(32)
//! ‖ deadline(8)`. The court witness is `tag=1 ‖ nonce0(32) ‖ nonce1(32) ‖
//! attested_envelope`. The lock replays the attested tape from the
//! commit-revealed seed, verifies each turn's signature is the acting player's,
//! extracts the winner, and binds the payout output to that winner.
//!
//! Fixtures (generated by the scratch match-generator — see task-4-report.md):
//!   * `fixture-court.bin`            — a completing 23-turn attested match,
//!                                      seed=1234, winner=team 1.
//!   * `fixture-attested-lockhashes.txt` — the two players' blake160 ids
//!                                      (same secp keys: priv byte31 = 1 / 2).
//! The revealing nonces (nonce0/nonce1) satisfy `derive_seed(n0,n1)==1234`.

use ckb_testtool::{
    ckb_types::{bytes::Bytes, core::TransactionBuilder, packed::*, prelude::*},
    context::Context,
};
use verifier::{create_world, decode_attested, decode_tape, derive_seed, step_world};

const ESCROW_BIN: &str = "target/riscv64imac-unknown-none-elf/release/escrow-lock";
const POT: u64 = 100_000;

/// The two revealing nonces. `nonce0` is the brute-forced counter (LE) whose
/// `derive_seed(nonce0, nonce1)` equals the fixture seed 1234; `nonce1` is zero.
fn nonces() -> ([u8; 32], [u8; 32]) {
    let mut n0 = [0u8; 32];
    n0[0..8].copy_from_slice(&2_273_457_623u64.to_le_bytes());
    let n1 = [0u8; 32];
    (n0, n1)
}

fn player_ids() -> ([u8; 20], [u8; 20]) {
    let txt = std::fs::read_to_string("../tests/fixture-attested-lockhashes.txt")
        .expect("fixture-attested-lockhashes.txt");
    let mut lines = txt.lines();
    let p0 = hex::decode(lines.next().unwrap().trim()).unwrap();
    let p1 = hex::decode(lines.next().unwrap().trim()).unwrap();
    (p0.try_into().unwrap(), p1.try_into().unwrap())
}

fn court_envelope() -> Vec<u8> {
    std::fs::read("../tests/fixture-court.bin").expect("fixture-court.bin")
}

/// Build the 112-byte escrow args.
fn build_args(p0: &[u8; 20], p1: &[u8; 20], c0: &[u8; 32], c1: &[u8; 32]) -> Vec<u8> {
    let mut a = Vec::with_capacity(112);
    a.extend_from_slice(p0);
    a.extend_from_slice(p1);
    a.extend_from_slice(c0);
    a.extend_from_slice(c1);
    a.extend_from_slice(&0u64.to_le_bytes()); // deadline (unused on court path)
    a
}

/// Build the court witness lock: tag(1) ‖ nonce0 ‖ nonce1 ‖ envelope.
fn court_witness(n0: &[u8; 32], n1: &[u8; 32], env: &[u8]) -> Vec<u8> {
    let mut w = Vec::with_capacity(1 + 64 + env.len());
    w.push(1u8);
    w.extend_from_slice(n0);
    w.extend_from_slice(n1);
    w.extend_from_slice(env);
    w
}

/// Replay the attested envelope on the host to learn the real winner (0/1/-1).
fn replay_winner(seed: i32, env: &[u8]) -> i64 {
    let blocks = decode_attested(env).expect("decode_attested");
    let mut w = create_world(seed, 1280, 720);
    for b in &blocks {
        for input in decode_tape(b.tape_bytes) {
            step_world(&mut w, &input);
        }
    }
    w.winner.expect("fixture match must reach a winner")
}

/// Assemble + verify a court-path spend. `outputs` is a list of (recipient_id,
/// capacity) pairs for the tx outputs (the payout cells).
fn run(
    args: Vec<u8>,
    witness_lock: Vec<u8>,
    outputs: &[(Vec<u8>, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);
    // Dummy code cell for the payout (recipient) locks. Output locks never run,
    // so any code_hash is fine; only the lock ARGS (the player id) are inspected.
    let recip_out = ctx.deploy_cell(Bytes::from_static(b"crypto-blast-recipient-lock"));

    let lock = ctx
        .build_script(&escrow_out, Bytes::from(args))
        .expect("build escrow lock");

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );
    let input = CellInput::new_builder().previous_output(input_cell).build();

    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(witness_lock)).pack())
        .build();

    let mut tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack());
    for (id, cap) in outputs {
        let recip_lock = ctx
            .build_script(&recip_out, Bytes::from(id.clone()))
            .expect("build recipient lock");
        tb = tb
            .output(
                CellOutput::new_builder()
                    .capacity(*cap)
                    .lock(recip_lock)
                    .build(),
            )
            .output_data(Bytes::new().pack());
    }
    let tx = ctx.complete_tx(tb.build());
    // Court path runs replay (~heavier than verifier-lock) + N bundled-k256 secp
    // recoveries; the 23-turn fixture measures ~278M cycles. 500M leaves headroom.
    ctx.verify_tx(&tx, 500_000_000).map(|c| c as u64)
}

/// Common valid setup: correct args + correct court witness, winner replayed.
fn valid_setup() -> (Vec<u8>, Vec<u8>, [u8; 20], [u8; 20], i64) {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let env = court_envelope();
    let seed = derive_seed(&n0, &n1);
    assert_eq!(seed, 1234, "nonces must derive the fixture seed");
    let winner = replay_winner(seed, &env);
    let args = build_args(&p0, &p1, &c0, &c1);
    let wit = court_witness(&n0, &n1, &env);
    (args, wit, p0, p1, winner)
}

#[test]
fn accepts_court_valid() {
    let (args, wit, p0, p1, winner) = valid_setup();
    // Pay the full pot to the replayed winner's id.
    let winner_id = match winner {
        0 => p0.to_vec(),
        1 => p1.to_vec(),
        _ => panic!("expected a decisive winner in the fixture, got {winner}"),
    };
    let r = run(args, wit, &[(winner_id, POT)]);
    assert!(
        r.is_ok(),
        "valid court spend must unlock, got {:?}",
        r.err()
    );
    if let Ok(cycles) = r {
        eprintln!("court-path cycles: {cycles}");
    }
}

#[test]
fn rejects_forged_move() {
    let (args, mut wit, _p0, p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");
    // Flip one byte inside the first turn's tape_bytes region of the envelope.
    // Envelope starts at witness offset 65: [0..2]=turn_count, [2..4]=block0_len,
    // then block0 tape — index 4 is the first tape byte. Offset in witness = 65+4.
    wit[65 + 4] ^= 0x01;
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "a forged move byte must reject");
}

#[test]
fn rejects_wrong_seed() {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    // Args carry the CORRECT commits; the witness reveals a WRONG nonce0 →
    // nonce-commit check fails (and the seed would differ anyway).
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let args = build_args(&p0, &p1, &c0, &c1);
    let bad_n0 = [0xAAu8; 32];
    let wit = court_witness(&bad_n0, &n1, &court_envelope());
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "wrong nonce (commit mismatch) must reject");
}

#[test]
fn rejects_payout_to_loser() {
    let (args, wit, p0, _p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");
    // Pay the full pot to the LOSER (player0) → must reject.
    let r = run(args, wit, &[(p0.to_vec(), POT)]);
    assert!(r.is_err(), "paying the loser must reject");
}
