//! ckb-testtool accept/reject proof for the Phase-4 escrow-lock COURT path (tag=1).
//!
//! The escrow cell holds the pot. Its lock is the `escrow-lock` script with
//! `args = expected_payout_code_hash(32) ‖ expected_payout_hash_type(1) ‖
//! player0_id(20) ‖ player1_id(20) ‖ nonce0_commit(32) ‖ nonce1_commit(32)
//! ‖ deadline(8)` (145 bytes). The court witness is
//! `tag=1 ‖ nonce0(32) ‖ nonce1(32) ‖ attested_envelope`. The lock replays the
//! attested tape from the commit-revealed seed, verifies each turn's signature
//! is the acting player's, extracts the winner, and binds the payout output to
//! that winner UNDER THE PINNED PAYOUT LOCK (code_hash + hash_type + args).
//!
//! Fixtures (generated by the scratch match-generator — see task-4-report.md):
//!   * `fixture-court.bin`            — a completing 23-turn attested match,
//!                                      seed=1234, winner=team 1.
//!   * `fixture-attested-lockhashes.txt` — the two players' blake160 ids
//!                                      (same secp keys: priv byte31 = 1 / 2).
//! The revealing nonces (nonce0/nonce1) satisfy `derive_seed(n0,n1)==1234`.

use ckb_testtool::{
    ckb_types::{
        bytes::Bytes,
        core::{ScriptHashType, TransactionBuilder},
        packed::*,
        prelude::*,
    },
    context::Context,
};
use k256::ecdsa::SigningKey;
use verifier::{create_world, decode_attested, decode_tape, derive_seed, step_world};

const ESCROW_BIN: &str = "target/riscv64imac-unknown-none-elf/release/escrow-lock";
const POT: u64 = 100_000;
const HALF: u64 = POT / 2;

/// The dummy recipient (payout) lock code. Output locks never execute, so its
/// body is irrelevant; only its IDENTITY (code_hash + hash_type) is pinned in
/// the escrow args and checked by the contract. We use `Data1` hash_type so the
/// code_hash is the deterministic blake2b data-hash of this byte string —
/// reproducible off-chain via `verifier::ckbhash`.
const RECIPIENT_LOCK_CODE: &[u8] = b"crypto-blast-recipient-lock";
/// ckb-types `HashType::Data1` byte (0=data, 1=type, 2=data1).
const HASH_TYPE_DATA1: u8 = 2;

/// The pinned payout-lock identity (code_hash, hash_type byte) that the test's
/// recipient outputs use and that gets embedded in the escrow args.
fn payout_lock_identity() -> ([u8; 32], u8) {
    (verifier::ckbhash(RECIPIENT_LOCK_CODE), HASH_TYPE_DATA1)
}

/// The two revealing nonces. `nonce0` is the brute-forced counter (LE) whose
/// `derive_seed(nonce0, nonce1)` equals the fixture seed 1234; `nonce1` is zero.
fn nonces() -> ([u8; 32], [u8; 32]) {
    let mut n0 = [0u8; 32];
    n0[0..8].copy_from_slice(&2_273_457_623u64.to_le_bytes());
    let n1 = [0u8; 32];
    (n0, n1)
}

fn player_ids() -> ([u8; 20], [u8; 20]) {
    let txt = std::fs::read_to_string("../tests/fixture-attested-lockhashes.txt")
        .expect("fixture-attested-lockhashes.txt");
    let mut lines = txt.lines();
    let p0 = hex::decode(lines.next().unwrap().trim()).unwrap();
    let p1 = hex::decode(lines.next().unwrap().trim()).unwrap();
    (p0.try_into().unwrap(), p1.try_into().unwrap())
}

fn court_envelope() -> Vec<u8> {
    std::fs::read("../tests/fixture-court.bin").expect("fixture-court.bin")
}

/// Build the 145-byte escrow args:
/// `payout_code_hash(32) ‖ payout_hash_type(1) ‖ p0(20) ‖ p1(20)
///  ‖ c0(32) ‖ c1(32) ‖ deadline(8)`.
fn build_args(p0: &[u8; 20], p1: &[u8; 20], c0: &[u8; 32], c1: &[u8; 32]) -> Vec<u8> {
    let (payout_code_hash, payout_hash_type) = payout_lock_identity();
    let mut a = Vec::with_capacity(145);
    a.extend_from_slice(&payout_code_hash);
    a.push(payout_hash_type);
    a.extend_from_slice(p0);
    a.extend_from_slice(p1);
    a.extend_from_slice(c0);
    a.extend_from_slice(c1);
    a.extend_from_slice(&0u64.to_le_bytes()); // deadline (unused on court path)
    assert_eq!(a.len(), 145, "escrow args must be 145 bytes");
    a
}

/// Build the court witness lock: tag(1) ‖ nonce0 ‖ nonce1 ‖ envelope.
fn court_witness(n0: &[u8; 32], n1: &[u8; 32], env: &[u8]) -> Vec<u8> {
    let mut w = Vec::with_capacity(1 + 64 + env.len());
    w.push(1u8);
    w.extend_from_slice(n0);
    w.extend_from_slice(n1);
    w.extend_from_slice(env);
    w
}

/// Replay the attested envelope on the host to learn the real winner (0/1/-1).
fn replay_winner(seed: i32, env: &[u8]) -> i64 {
    let blocks = decode_attested(env).expect("decode_attested");
    let mut w = create_world(seed, 1280, 720);
    for b in &blocks {
        for input in decode_tape(b.tape_bytes) {
            step_world(&mut w, &input);
        }
    }
    w.winner.expect("fixture match must reach a winner")
}

/// Build the canonical PINNED payout lock for `id`: the code_hash + hash_type
/// embedded in the escrow args, with the recipient's blake160 as args. This is
/// the only lock the contract counts toward the payout.
fn pinned_payout_lock(id: &[u8]) -> Script {
    let (code_hash, _) = payout_lock_identity();
    Script::new_builder()
        .code_hash(code_hash.pack())
        .hash_type(ScriptHashType::Data1)
        .args(Bytes::from(id.to_vec()).pack())
        .build()
}

/// Assemble + verify a court-path spend with explicit output LOCKS. Used by the
/// adversarial test to plant a winner-args output under an attacker code_hash.
fn run_with_locks(
    args: Vec<u8>,
    witness_lock: Vec<u8>,
    outputs: &[(Script, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);

    let lock = ctx
        .build_script(&escrow_out, Bytes::from(args))
        .expect("build escrow lock");

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );
    let input = CellInput::new_builder().previous_output(input_cell).build();

    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(witness_lock)).pack())
        .build();

    let mut tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack());
    for (recip_lock, cap) in outputs {
        tb = tb
            .output(
                CellOutput::new_builder()
                    .capacity(*cap)
                    .lock(recip_lock.clone())
                    .build(),
            )
            .output_data(Bytes::new().pack());
    }
    let tx = ctx.complete_tx(tb.build());
    // Court path runs replay (~heavier than verifier-lock) + N bundled-k256 secp
    // recoveries; the 23-turn fixture measures ~278M cycles. 500M leaves headroom.
    ctx.verify_tx(&tx, 500_000_000).map(|c| c as u64)
}

/// Assemble + verify a court-path spend. `outputs` is a list of (recipient_id,
/// capacity) pairs; each gets the canonical PINNED payout lock.
fn run(
    args: Vec<u8>,
    witness_lock: Vec<u8>,
    outputs: &[(Vec<u8>, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let locks: Vec<(Script, u64)> = outputs
        .iter()
        .map(|(id, cap)| (pinned_payout_lock(id), *cap))
        .collect();
    run_with_locks(args, witness_lock, &locks)
}

/// Common valid setup: correct args + correct court witness, winner replayed.
fn valid_setup() -> (Vec<u8>, Vec<u8>, [u8; 20], [u8; 20], i64) {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let env = court_envelope();
    let seed = derive_seed(&n0, &n1);
    assert_eq!(seed, 1234, "nonces must derive the fixture seed");
    let winner = replay_winner(seed, &env);
    let args = build_args(&p0, &p1, &c0, &c1);
    let wit = court_witness(&n0, &n1, &env);
    (args, wit, p0, p1, winner)
}

#[test]
fn accepts_court_valid() {
    let (args, wit, p0, p1, winner) = valid_setup();
    // Pay the full pot to the replayed winner's id.
    let winner_id = match winner {
        0 => p0.to_vec(),
        1 => p1.to_vec(),
        _ => panic!("expected a decisive winner in the fixture, got {winner}"),
    };
    let r = run(args, wit, &[(winner_id, POT)]);
    assert!(
        r.is_ok(),
        "valid court spend must unlock, got {:?}",
        r.err()
    );
    if let Ok(cycles) = r {
        eprintln!("court-path cycles: {cycles}");
    }
}

#[test]
fn rejects_forged_move() {
    let (args, mut wit, _p0, p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");
    // Flip one byte inside the first turn's tape_bytes region of the envelope.
    // Envelope starts at witness offset 65: [0..2]=turn_count, [2..4]=block0_len,
    // then block0 tape — index 4 is the first tape byte. Offset in witness = 65+4.
    wit[65 + 4] ^= 0x01;
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "a forged move byte must reject");
}

#[test]
fn rejects_wrong_seed() {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    // Args carry the CORRECT commits; the witness reveals a WRONG nonce0 →
    // nonce-commit check fails (and the seed would differ anyway).
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let args = build_args(&p0, &p1, &c0, &c1);
    let bad_n0 = [0xAAu8; 32];
    let wit = court_witness(&bad_n0, &n1, &court_envelope());
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "wrong nonce (commit mismatch) must reject");
}

#[test]
fn rejects_payout_to_loser() {
    let (args, wit, p0, _p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");
    // Pay the full pot to the LOSER (player0) → must reject.
    let r = run(args, wit, &[(p0.to_vec(), POT)]);
    assert!(r.is_err(), "paying the loser must reject");
}

/// CRITICAL prize-theft regression: a losing player submits the court spend and
/// creates an output with `capacity == pot` and `lock.args == winner_blake160`
/// but a `code_hash` THEY control (here a bogus / always-success-style code_hash
/// that is NOT the pinned payout code_hash). The args-only binding would have
/// passed and let the attacker sweep the pot. With the code_hash + hash_type pin
/// the output is NOT counted toward the winner → the spend MUST reject.
// ===========================================================================
// Path 0 — HAPPY (mutual-signed payout)  and  Path 2 — REFUND (timeout split)
// ===========================================================================

/// The two fixture player secp keys: scalars 1 and 2 (priv byte31 = 1 / 2) —
/// the same keys that produced `fixture-attested-lockhashes.txt`, so their
/// blake160 ids are exactly `player_ids()`.
fn signing_keys() -> (SigningKey, SigningKey) {
    let mut k0 = [0u8; 32];
    k0[31] = 1;
    let mut k1 = [0u8; 32];
    k1[31] = 2;
    (
        SigningKey::from_slice(&k0).expect("player0 key"),
        SigningKey::from_slice(&k1).expect("player1 key"),
    )
}

/// A wrong key (scalar 9) used to forge a "valid-but-wrong-signer" signature.
fn wrong_key() -> SigningKey {
    let mut k = [0u8; 32];
    k[31] = 9;
    SigningKey::from_slice(&k).expect("wrong key")
}

/// Produce a `[v(1) ‖ r(32) ‖ s(32)]` recoverable signature over the 32-byte
/// prehash — the layout the escrow-lock recovers (recovery byte first, v∈{0,1}).
fn sign_recoverable(key: &SigningKey, msg: &[u8; 32]) -> Vec<u8> {
    let (sig, recid) = key.sign_prehash_recoverable(msg).expect("sign");
    let mut out = Vec::with_capacity(65);
    out.push(recid.to_byte());
    out.extend_from_slice(&sig.to_bytes());
    out
}

/// 145-byte escrow args with an explicit `deadline_block` (refund path reads it;
/// happy/court ignore it). Commits are zero — happy/refund don't use them.
fn build_args_deadline(
    p0: &[u8; 20],
    p1: &[u8; 20],
    c0: &[u8; 32],
    c1: &[u8; 32],
    deadline: u64,
) -> Vec<u8> {
    let mut a = build_args(p0, p1, c0, c1);
    // Overwrite the trailing 8-byte deadline (build_args wrote 0).
    a.truncate(137);
    a.extend_from_slice(&deadline.to_le_bytes());
    assert_eq!(a.len(), 145);
    a
}

/// Assemble + verify a Path-0 (happy) spend. The signed message binds the
/// escrow's RUNTIME OutPoint, so the cell is created first, then both keys sign
/// `blake2b(outpoint ‖ agreed_winner)`. `outputs` get the pinned payout lock.
fn run_happy(
    args: Vec<u8>,
    agreed_winner: u8,
    key0: &SigningKey,
    key1: &SigningKey,
    outputs: &[(Vec<u8>, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);
    let lock = ctx
        .build_script(&escrow_out, Bytes::from(args))
        .expect("build escrow lock");

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );

    // message = blake2b(escrow_input_outpoint ‖ agreed_winner).
    let mut preimage = input_cell.as_slice().to_vec();
    preimage.push(agreed_winner);
    let msg = verifier::ckbhash(&preimage);

    let mut witness_lock = Vec::with_capacity(1 + 1 + 65 + 65);
    witness_lock.push(0u8); // tag = 0 (happy)
    witness_lock.push(agreed_winner);
    witness_lock.extend_from_slice(&sign_recoverable(key0, &msg));
    witness_lock.extend_from_slice(&sign_recoverable(key1, &msg));

    let input = CellInput::new_builder()
        .previous_output(input_cell)
        .build();
    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(witness_lock)).pack())
        .build();

    let mut tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack());
    for (id, cap) in outputs {
        tb = tb
            .output(
                CellOutput::new_builder()
                    .capacity(*cap)
                    .lock(pinned_payout_lock(id))
                    .build(),
            )
            .output_data(Bytes::new().pack());
    }
    let tx = ctx.complete_tx(tb.build());
    ctx.verify_tx(&tx, 200_000_000).map(|c| c as u64)
}

/// Assemble + verify a Path-2 (refund) spend with the GroupInput `since` set to
/// `since` (an absolute block number when the top byte is 0). `outputs` get the
/// pinned payout lock.
fn run_refund(
    args: Vec<u8>,
    since: u64,
    outputs: &[(Vec<u8>, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);
    let lock = ctx
        .build_script(&escrow_out, Bytes::from(args))
        .expect("build escrow lock");

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );
    // Absolute-block-number since: top byte 0, value = block height.
    let since_packed: Uint64 = since.pack();
    let input = CellInput::new_builder()
        .since(since_packed)
        .previous_output(input_cell)
        .build();
    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(vec![2u8])).pack()) // tag = 2 (refund)
        .build();

    let mut tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack());
    for (id, cap) in outputs {
        tb = tb
            .output(
                CellOutput::new_builder()
                    .capacity(*cap)
                    .lock(pinned_payout_lock(id))
                    .build(),
            )
            .output_data(Bytes::new().pack());
    }
    let tx = ctx.complete_tx(tb.build());
    ctx.verify_tx(&tx, 200_000_000).map(|c| c as u64)
}

#[test]
fn accepts_happy_both_sign() {
    let (p0, p1) = player_ids();
    let (k0, k1) = signing_keys();
    let args = build_args(&p0, &p1, &[0u8; 32], &[0u8; 32]);
    // Both players agree player1 won; pay the full pot to p1 under the pinned lock.
    let r = run_happy(args, 1, &k0, &k1, &[(p1.to_vec(), POT)]);
    assert!(
        r.is_ok(),
        "happy spend with both valid sigs + correct payout must unlock, got {:?}",
        r.err()
    );
}

#[test]
fn rejects_happy_single_sig() {
    let (p0, p1) = player_ids();
    let (k0, _k1) = signing_keys();
    let wrong = wrong_key();
    let args = build_args(&p0, &p1, &[0u8; 32], &[0u8; 32]);
    // sig0 is player0's; sig1 is signed by a WRONG key → player1's sig invalid.
    let r = run_happy(args, 1, &k0, &wrong, &[(p1.to_vec(), POT)]);
    assert!(
        r.is_err(),
        "happy spend missing a valid player1 sig must reject (both must sign)"
    );
}

#[test]
fn accepts_happy_draw_split() {
    let (p0, p1) = player_ids();
    let (k0, k1) = signing_keys();
    let args = build_args(&p0, &p1, &[0u8; 32], &[0u8; 32]);
    // agreed_winner = 255 (draw): two outputs, 50/50 under the pinned lock.
    let r = run_happy(
        args,
        255,
        &k0,
        &k1,
        &[(p0.to_vec(), HALF), (p1.to_vec(), HALF)],
    );
    assert!(
        r.is_ok(),
        "happy draw with a 50/50 split must unlock, got {:?}",
        r.err()
    );
}

#[test]
fn accepts_refund_after_deadline() {
    let (p0, p1) = player_ids();
    let deadline = 1000u64;
    let args = build_args_deadline(&p0, &p1, &[0u8; 32], &[0u8; 32], deadline);
    // since == deadline (absolute block) → opens the refund; 50/50 split.
    let r = run_refund(args, deadline, &[(p0.to_vec(), HALF), (p1.to_vec(), HALF)]);
    assert!(
        r.is_ok(),
        "refund at/after the deadline with a 50/50 split must unlock, got {:?}",
        r.err()
    );
}

#[test]
fn rejects_refund_before_deadline() {
    let (p0, p1) = player_ids();
    let deadline = 1000u64;
    let args = build_args_deadline(&p0, &p1, &[0u8; 32], &[0u8; 32], deadline);
    // since == deadline-1 < deadline → refund must NOT open.
    let r = run_refund(
        args,
        deadline - 1,
        &[(p0.to_vec(), HALF), (p1.to_vec(), HALF)],
    );
    assert!(r.is_err(), "refund before the deadline must reject");
}

#[test]
fn rejects_payout_to_winner_args_wrong_lock() {
    let (args, wit, _p0, p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");

    // Correct winner ARGS, but an attacker-controlled lock SCRIPT (different
    // code_hash from the pinned payout lock). hash_type is also Data1 to prove
    // the rejection is driven by the code_hash mismatch, not hash_type.
    let attacker_lock = Script::new_builder()
        .code_hash([0xFFu8; 32].pack()) // NOT verifier::ckbhash(RECIPIENT_LOCK_CODE)
        .hash_type(ScriptHashType::Data1)
        .args(Bytes::from(p1.to_vec()).pack())
        .build();

    let r = run_with_locks(args, wit, &[(attacker_lock, POT)]);
    assert!(
        r.is_err(),
        "payout to winner-args under an attacker-controlled lock must reject (prize-theft blocked)"
    );
}
