//! ckb-testtool accept/reject proof for the Phase-4 escrow-lock COURT path (tag=1).
//!
//! The escrow cell holds the pot. Its lock is the `escrow-lock` script with
//! `args = expected_payout_code_hash(32) ‖ expected_payout_hash_type(1) ‖
//! player0_id(20) ‖ player1_id(20) ‖ nonce0_commit(32) ‖ nonce1_commit(32)
//! ‖ deadline(8)` (145 bytes). The court witness is
//! `tag=1 ‖ nonce0(32) ‖ nonce1(32) ‖ attested_envelope`. The lock replays the
//! attested tape from the commit-revealed seed, verifies each turn's signature
//! is the acting player's, extracts the winner, and binds the payout output to
//! that winner UNDER THE PINNED PAYOUT LOCK (code_hash + hash_type + args).
//!
//! Fixtures (generated by the scratch match-generator — see task-4-report.md):
//!   * `fixture-court.bin`            — a completing 23-turn attested match,
//!                                      seed=1234, winner=team 1.
//!   * `fixture-attested-lockhashes.txt` — the two players' blake160 ids
//!                                      (same secp keys: priv byte31 = 1 / 2).
//! The revealing nonces (nonce0/nonce1) satisfy `derive_seed(n0,n1)==1234`.

use ckb_testtool::{
    ckb_types::{
        bytes::Bytes,
        core::{ScriptHashType, TransactionBuilder},
        packed::*,
        prelude::*,
    },
    context::Context,
};
use k256::ecdsa::SigningKey;
use verifier::{
    court_chain_genesis, court_chain_step, create_world, decode_court_envelope, decode_tape,
    derive_seed, encode_court_envelope, step_world,
};

const ESCROW_BIN: &str = "target/riscv64imac-unknown-none-elf/release/escrow-lock";
const POT: u64 = 100_000;
const HALF: u64 = POT / 2;

/// The dummy recipient (payout) lock code. Output locks never execute, so its
/// body is irrelevant; only its IDENTITY (code_hash + hash_type) is pinned in
/// the escrow args and checked by the contract. We use `Data1` hash_type so the
/// code_hash is the deterministic blake2b data-hash of this byte string —
/// reproducible off-chain via `verifier::ckbhash`.
const RECIPIENT_LOCK_CODE: &[u8] = b"crypto-blast-recipient-lock";
/// ckb-types `HashType::Data1` byte (0=data, 1=type, 2=data1).
const HASH_TYPE_DATA1: u8 = 2;

/// The pinned payout-lock identity (code_hash, hash_type byte) that the test's
/// recipient outputs use and that gets embedded in the escrow args.
fn payout_lock_identity() -> ([u8; 32], u8) {
    (verifier::ckbhash(RECIPIENT_LOCK_CODE), HASH_TYPE_DATA1)
}

/// The dummy forfeit-lock code. Like the recipient lock, its body is irrelevant
/// (output locks never execute); only its IDENTITY is pinned in the escrow args
/// (args[153..186]) and checked against the pending-forfeit output cell's lock.
const FORFEIT_LOCK_CODE: &[u8] = b"crypto-blast-forfeit-lock";

/// The funder-set reveal window embedded in the escrow args (args[145..153]).
/// forfeit_deadline = claim_since + REVEAL_WINDOW.
const REVEAL_WINDOW: u64 = 100;

/// The pinned forfeit-lock identity (code_hash, hash_type byte) that the
/// pending-forfeit output cell uses and that gets embedded in the escrow args.
fn forfeit_lock_identity() -> ([u8; 32], u8) {
    (verifier::ckbhash(FORFEIT_LOCK_CODE), HASH_TYPE_DATA1)
}

/// The two revealing nonces. `nonce0` is the brute-forced counter (LE) whose
/// `derive_seed(nonce0, nonce1)` equals the fixture seed 1234; `nonce1` is zero.
fn nonces() -> ([u8; 32], [u8; 32]) {
    let mut n0 = [0u8; 32];
    n0[0..8].copy_from_slice(&2_273_457_623u64.to_le_bytes());
    let n1 = [0u8; 32];
    (n0, n1)
}

fn player_ids() -> ([u8; 20], [u8; 20]) {
    let txt = std::fs::read_to_string("../tests/fixture-attested-lockhashes.txt")
        .expect("fixture-attested-lockhashes.txt");
    let mut lines = txt.lines();
    let p0 = hex::decode(lines.next().unwrap().trim()).unwrap();
    let p1 = hex::decode(lines.next().unwrap().trim()).unwrap();
    (p0.try_into().unwrap(), p1.try_into().unwrap())
}

fn court_envelope() -> Vec<u8> {
    std::fs::read("../tests/fixture-court.bin").expect("fixture-court.bin")
}

/// Build the 186-byte escrow args:
/// `payout_code_hash(32) ‖ payout_hash_type(1) ‖ p0(20) ‖ p1(20)
///  ‖ c0(32) ‖ c1(32) ‖ deadline(8) ‖ reveal_window(8)
///  ‖ forfeit_lock_code_hash(32) ‖ forfeit_lock_hash_type(1)`.
/// The happy/court/refund paths ignore the trailing reveal_window + forfeit pin.
fn build_args(p0: &[u8; 20], p1: &[u8; 20], c0: &[u8; 32], c1: &[u8; 32]) -> Vec<u8> {
    let (payout_code_hash, payout_hash_type) = payout_lock_identity();
    let (forfeit_code_hash, forfeit_hash_type) = forfeit_lock_identity();
    let mut a = Vec::with_capacity(186);
    a.extend_from_slice(&payout_code_hash);
    a.push(payout_hash_type);
    a.extend_from_slice(p0);
    a.extend_from_slice(p1);
    a.extend_from_slice(c0);
    a.extend_from_slice(c1);
    a.extend_from_slice(&0u64.to_le_bytes()); // deadline (unused on court path)
    a.extend_from_slice(&REVEAL_WINDOW.to_le_bytes()); // reveal_window (forfeit path)
    a.extend_from_slice(&forfeit_code_hash); // forfeit-lock PIN (forfeit path)
    a.push(forfeit_hash_type);
    assert_eq!(a.len(), 186, "escrow args must be 186 bytes");
    a
}

/// Build the court witness lock: tag(1) ‖ nonce0 ‖ nonce1 ‖ envelope.
fn court_witness(n0: &[u8; 32], n1: &[u8; 32], env: &[u8]) -> Vec<u8> {
    let mut w = Vec::with_capacity(1 + 64 + env.len());
    w.push(1u8);
    w.extend_from_slice(n0);
    w.extend_from_slice(n1);
    w.extend_from_slice(env);
    w
}

/// Replay the attested envelope on the host to learn the real winner (0/1/-1).
fn replay_winner(seed: i32, env: &[u8]) -> i64 {
    let e = decode_court_envelope(env).expect("decode_court_envelope");
    let mut w = create_world(seed, 1280, 720);
    for tape in &e.tapes {
        for input in decode_tape(tape) {
            step_world(&mut w, &input);
        }
    }
    w.winner.expect("fixture match must reach a winner")
}

/// Build the canonical PINNED payout lock for `id`: the code_hash + hash_type
/// embedded in the escrow args, with the recipient's blake160 as args. This is
/// the only lock the contract counts toward the payout.
fn pinned_payout_lock(id: &[u8]) -> Script {
    let (code_hash, _) = payout_lock_identity();
    Script::new_builder()
        .code_hash(code_hash.pack())
        .hash_type(ScriptHashType::Data1)
        .args(Bytes::from(id.to_vec()).pack())
        .build()
}

/// Assemble + verify a court-path spend with explicit output LOCKS. Used by the
/// adversarial test to plant a winner-args output under an attacker code_hash.
fn run_with_locks(
    args: Vec<u8>,
    witness_lock: Vec<u8>,
    outputs: &[(Script, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);

    let lock = ctx
        .build_script(&escrow_out, Bytes::from(args))
        .expect("build escrow lock");

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );
    let input = CellInput::new_builder().previous_output(input_cell).build();

    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(witness_lock)).pack())
        .build();

    let mut tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack());
    for (recip_lock, cap) in outputs {
        tb = tb
            .output(
                CellOutput::new_builder()
                    .capacity(*cap)
                    .lock(recip_lock.clone())
                    .build(),
            )
            .output_data(Bytes::new().pack());
    }
    let tx = ctx.complete_tx(tb.build());
    // Interleaved-chain court verifies 2 recoveries (constant in turn count),
    // but the 23-turn match REPLAY (~136M) dominates: ~148M total (measured),
    // down from ~278M (was 23 per-turn recoveries). Under the 200M per-tx ceiling.
    ctx.verify_tx(&tx, 200_000_000).map(|c| c as u64)
}

/// Assemble + verify a court-path spend. `outputs` is a list of (recipient_id,
/// capacity) pairs; each gets the canonical PINNED payout lock.
fn run(
    args: Vec<u8>,
    witness_lock: Vec<u8>,
    outputs: &[(Vec<u8>, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let locks: Vec<(Script, u64)> = outputs
        .iter()
        .map(|(id, cap)| (pinned_payout_lock(id), *cap))
        .collect();
    run_with_locks(args, witness_lock, &locks)
}

/// Common valid setup: correct args + correct court witness, winner replayed.
fn valid_setup() -> (Vec<u8>, Vec<u8>, [u8; 20], [u8; 20], i64) {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let env = court_envelope();
    let seed = derive_seed(&n0, &n1);
    assert_eq!(seed, 1234, "nonces must derive the fixture seed");
    let winner = replay_winner(seed, &env);
    let args = build_args(&p0, &p1, &c0, &c1);
    let wit = court_witness(&n0, &n1, &env);
    (args, wit, p0, p1, winner)
}

#[test]
fn accepts_court_valid() {
    let (args, wit, p0, p1, winner) = valid_setup();
    // Pay the full pot to the replayed winner's id.
    let winner_id = match winner {
        0 => p0.to_vec(),
        1 => p1.to_vec(),
        _ => panic!("expected a decisive winner in the fixture, got {winner}"),
    };
    let r = run(args, wit, &[(winner_id, POT)]);
    assert!(
        r.is_ok(),
        "valid court spend must unlock, got {:?}",
        r.err()
    );
    if let Ok(cycles) = r {
        eprintln!("court-path cycles: {cycles}");
    }
}

#[test]
fn rejects_forged_move() {
    let (args, mut wit, _p0, p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");
    // Flip one byte inside the first turn's tape_bytes region of the envelope.
    // Envelope starts at witness offset 65: [0..2]=turn_count, [2..4]=block0_len,
    // then block0 tape — index 4 is the first tape byte. Offset in witness = 65+4.
    wit[65 + 4] ^= 0x01;
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "a forged move byte must reject");
}

#[test]
fn rejects_wrong_seed() {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    // Args carry the CORRECT commits; the witness reveals a WRONG nonce0 →
    // nonce-commit check fails (and the seed would differ anyway).
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let args = build_args(&p0, &p1, &c0, &c1);
    let bad_n0 = [0xAAu8; 32];
    let wit = court_witness(&bad_n0, &n1, &court_envelope());
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "wrong nonce (commit mismatch) must reject");
}

#[test]
fn rejects_payout_to_loser() {
    let (args, wit, p0, _p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");
    // Pay the full pot to the LOSER (player0) → must reject.
    let r = run(args, wit, &[(p0.to_vec(), POT)]);
    assert!(r.is_err(), "paying the loser must reject");
}

/// CRITICAL prize-theft regression: a losing player submits the court spend and
/// creates an output with `capacity == pot` and `lock.args == winner_blake160`
/// but a `code_hash` THEY control (here a bogus / always-success-style code_hash
/// that is NOT the pinned payout code_hash). The args-only binding would have
/// passed and let the attacker sweep the pot. With the code_hash + hash_type pin
/// the output is NOT counted toward the winner → the spend MUST reject.
// ===========================================================================
// Path 0 — HAPPY (mutual-signed payout)  and  Path 2 — REFUND (timeout split)
// ===========================================================================

/// The two fixture player secp keys: scalars 1 and 2 (priv byte31 = 1 / 2) —
/// the same keys that produced `fixture-attested-lockhashes.txt`, so their
/// blake160 ids are exactly `player_ids()`.
fn signing_keys() -> (SigningKey, SigningKey) {
    let mut k0 = [0u8; 32];
    k0[31] = 1;
    let mut k1 = [0u8; 32];
    k1[31] = 2;
    (
        SigningKey::from_slice(&k0).expect("player0 key"),
        SigningKey::from_slice(&k1).expect("player1 key"),
    )
}

/// A wrong key (scalar 9) used to forge a "valid-but-wrong-signer" signature.
fn wrong_key() -> SigningKey {
    let mut k = [0u8; 32];
    k[31] = 9;
    SigningKey::from_slice(&k).expect("wrong key")
}

/// Produce a `[v(1) ‖ r(32) ‖ s(32)]` recoverable signature over the 32-byte
/// prehash — the layout the escrow-lock recovers (recovery byte first, v∈{0,1}).
fn sign_recoverable(key: &SigningKey, msg: &[u8; 32]) -> Vec<u8> {
    let (sig, recid) = key.sign_prehash_recoverable(msg).expect("sign");
    let mut out = Vec::with_capacity(65);
    out.push(recid.to_byte());
    out.extend_from_slice(&sig.to_bytes());
    out
}

/// 186-byte escrow args with an explicit `deadline_block` (refund path reads it;
/// happy/court ignore it). Commits are zero — happy/refund don't use them.
fn build_args_deadline(
    p0: &[u8; 20],
    p1: &[u8; 20],
    c0: &[u8; 32],
    c1: &[u8; 32],
    deadline: u64,
) -> Vec<u8> {
    let mut a = build_args(p0, p1, c0, c1);
    // Overwrite the 8-byte deadline at [137..145] (build_args wrote 0), then
    // re-append reveal_window + forfeit pin so the args stay 186 bytes.
    a.truncate(137);
    a.extend_from_slice(&deadline.to_le_bytes());
    let (forfeit_code_hash, forfeit_hash_type) = forfeit_lock_identity();
    a.extend_from_slice(&REVEAL_WINDOW.to_le_bytes());
    a.extend_from_slice(&forfeit_code_hash);
    a.push(forfeit_hash_type);
    assert_eq!(a.len(), 186);
    a
}

/// Assemble + verify a Path-0 (happy) spend. The signed message binds the
/// escrow's RUNTIME OutPoint, so the cell is created first, then both keys sign
/// `blake2b(outpoint ‖ agreed_winner)`. `outputs` get the pinned payout lock.
fn run_happy(
    args: Vec<u8>,
    agreed_winner: u8,
    key0: &SigningKey,
    key1: &SigningKey,
    outputs: &[(Vec<u8>, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);
    let lock = ctx
        .build_script(&escrow_out, Bytes::from(args))
        .expect("build escrow lock");

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );

    // message = blake2b(escrow_input_outpoint ‖ agreed_winner).
    let mut preimage = input_cell.as_slice().to_vec();
    preimage.push(agreed_winner);
    let msg = verifier::ckbhash(&preimage);

    let mut witness_lock = Vec::with_capacity(1 + 1 + 65 + 65);
    witness_lock.push(0u8); // tag = 0 (happy)
    witness_lock.push(agreed_winner);
    witness_lock.extend_from_slice(&sign_recoverable(key0, &msg));
    witness_lock.extend_from_slice(&sign_recoverable(key1, &msg));

    let input = CellInput::new_builder()
        .previous_output(input_cell)
        .build();
    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(witness_lock)).pack())
        .build();

    let mut tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack());
    for (id, cap) in outputs {
        tb = tb
            .output(
                CellOutput::new_builder()
                    .capacity(*cap)
                    .lock(pinned_payout_lock(id))
                    .build(),
            )
            .output_data(Bytes::new().pack());
    }
    let tx = ctx.complete_tx(tb.build());
    ctx.verify_tx(&tx, 200_000_000).map(|c| c as u64)
}

/// Assemble + verify a Path-2 (refund) spend with the GroupInput `since` set to
/// `since` (an absolute block number when the top byte is 0). `outputs` get the
/// pinned payout lock.
fn run_refund(
    args: Vec<u8>,
    since: u64,
    outputs: &[(Vec<u8>, u64)],
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);
    let lock = ctx
        .build_script(&escrow_out, Bytes::from(args))
        .expect("build escrow lock");

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );
    // Absolute-block-number since: top byte 0, value = block height.
    let since_packed: Uint64 = since.pack();
    let input = CellInput::new_builder()
        .since(since_packed)
        .previous_output(input_cell)
        .build();
    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(vec![2u8])).pack()) // tag = 2 (refund)
        .build();

    let mut tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack());
    for (id, cap) in outputs {
        tb = tb
            .output(
                CellOutput::new_builder()
                    .capacity(*cap)
                    .lock(pinned_payout_lock(id))
                    .build(),
            )
            .output_data(Bytes::new().pack());
    }
    let tx = ctx.complete_tx(tb.build());
    ctx.verify_tx(&tx, 200_000_000).map(|c| c as u64)
}

#[test]
fn accepts_happy_both_sign() {
    let (p0, p1) = player_ids();
    let (k0, k1) = signing_keys();
    let args = build_args(&p0, &p1, &[0u8; 32], &[0u8; 32]);
    // Both players agree player1 won; pay the full pot to p1 under the pinned lock.
    let r = run_happy(args, 1, &k0, &k1, &[(p1.to_vec(), POT)]);
    assert!(
        r.is_ok(),
        "happy spend with both valid sigs + correct payout must unlock, got {:?}",
        r.err()
    );
}

#[test]
fn rejects_happy_single_sig() {
    let (p0, p1) = player_ids();
    let (k0, _k1) = signing_keys();
    let wrong = wrong_key();
    let args = build_args(&p0, &p1, &[0u8; 32], &[0u8; 32]);
    // sig0 is player0's; sig1 is signed by a WRONG key → player1's sig invalid.
    let r = run_happy(args, 1, &k0, &wrong, &[(p1.to_vec(), POT)]);
    assert!(
        r.is_err(),
        "happy spend missing a valid player1 sig must reject (both must sign)"
    );
}

#[test]
fn accepts_happy_draw_split() {
    let (p0, p1) = player_ids();
    let (k0, k1) = signing_keys();
    let args = build_args(&p0, &p1, &[0u8; 32], &[0u8; 32]);
    // agreed_winner = 255 (draw): two outputs, 50/50 under the pinned lock.
    let r = run_happy(
        args,
        255,
        &k0,
        &k1,
        &[(p0.to_vec(), HALF), (p1.to_vec(), HALF)],
    );
    assert!(
        r.is_ok(),
        "happy draw with a 50/50 split must unlock, got {:?}",
        r.err()
    );
}

#[test]
fn accepts_refund_after_deadline() {
    let (p0, p1) = player_ids();
    let deadline = 1000u64;
    let args = build_args_deadline(&p0, &p1, &[0u8; 32], &[0u8; 32], deadline);
    // since == deadline (absolute block) → opens the refund; 50/50 split.
    let r = run_refund(args, deadline, &[(p0.to_vec(), HALF), (p1.to_vec(), HALF)]);
    assert!(
        r.is_ok(),
        "refund at/after the deadline with a 50/50 split must unlock, got {:?}",
        r.err()
    );
}

#[test]
fn rejects_refund_before_deadline() {
    let (p0, p1) = player_ids();
    let deadline = 1000u64;
    let args = build_args_deadline(&p0, &p1, &[0u8; 32], &[0u8; 32], deadline);
    // since == deadline-1 < deadline → refund must NOT open.
    let r = run_refund(
        args,
        deadline - 1,
        &[(p0.to_vec(), HALF), (p1.to_vec(), HALF)],
    );
    assert!(r.is_err(), "refund before the deadline must reject");
}

#[test]
fn rejects_payout_to_winner_args_wrong_lock() {
    let (args, wit, _p0, p1, winner) = valid_setup();
    assert_eq!(winner, 1, "fixture winner is team 1");

    // Correct winner ARGS, but an attacker-controlled lock SCRIPT (different
    // code_hash from the pinned payout lock). hash_type is also Data1 to prove
    // the rejection is driven by the code_hash mismatch, not hash_type.
    let attacker_lock = Script::new_builder()
        .code_hash([0xFFu8; 32].pack()) // NOT verifier::ckbhash(RECIPIENT_LOCK_CODE)
        .hash_type(ScriptHashType::Data1)
        .args(Bytes::from(p1.to_vec()).pack())
        .build();

    let r = run_with_locks(args, wit, &[(attacker_lock, POT)]);
    assert!(
        r.is_err(),
        "payout to winner-args under an attacker-controlled lock must reject (prize-theft blocked)"
    );
}

#[test]
fn rejects_swapped_final_sigs() {
    // Swapping sig0/sig1 makes each recover to the WRONG player id.
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let env = court_envelope();
    let e = decode_court_envelope(&env).expect("decode");
    let swapped = encode_court_envelope(&e.tapes, e.sig1, e.sig0); // sigs swapped
    let args = build_args(&p0, &p1, &c0, &c1);
    let wit = court_witness(&n0, &n1, &swapped);
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "swapped final-head sigs must reject (E_ACTOR_MISMATCH)");
}

#[test]
fn rejects_truncated_no_winner() {
    // Dropping the final turn yields a non-terminal replay → no winner.
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let env = court_envelope();
    let e = decode_court_envelope(&env).expect("decode");
    let n = e.tapes.len();
    let truncated = encode_court_envelope(&e.tapes[..n - 1], e.sig0, e.sig1);
    let args = build_args(&p0, &p1, &c0, &c1);
    let wit = court_witness(&n0, &n1, &truncated);
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "truncated match must reject (E_NO_WINNER)");
}

#[test]
fn rejects_player_with_zero_turns() {
    // A single-turn envelope leaves player1 with no head → E_PLAYER_NO_TURNS,
    // checked BEFORE signature recovery (so dummy sigs are fine).
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let env = court_envelope();
    let e = decode_court_envelope(&env).expect("decode");
    let one = encode_court_envelope(&e.tapes[..1], &[0u8; 65], &[0u8; 65]);
    let args = build_args(&p0, &p1, &c0, &c1);
    let wit = court_witness(&n0, &n1, &one);
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "a player with zero turns must reject (E_PLAYER_NO_TURNS)");
}

#[test]
fn rejects_trailing_bytes() {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let mut env = court_envelope();
    env.push(0u8); // strict-length violation
    let args = build_args(&p0, &p1, &c0, &c1);
    let wit = court_witness(&n0, &n1, &env);
    let r = run(args, wit, &[(p1.to_vec(), POT)]);
    assert!(r.is_err(), "trailing bytes must reject (E_DECODE_ATTESTED)");
}

// ===========================================================================
// Path 3 — FORFEIT-CLAIM (tag=3 → pending-forfeit cell)
// ===========================================================================

/// A built forfeit-claim scenario: everything `run_forfeit_claim` needs to assemble
/// the tag-3 spend AND to reconstruct the expected 316-byte pending-forfeit blob.
struct ForfeitSetup {
    /// 186-byte escrow `lock.args`.
    args: Vec<u8>,
    /// tag-3 witness lock: `tag(1) ‖ nonce0(32) ‖ nonce1(32) ‖ evidence_body`.
    witness_lock: Vec<u8>,
    /// The mutually-signed last completed head (folded over the prefix).
    head_k: [u8; 32],
    /// `prefix_tapes.len()` — the stalled turn index.
    stalled_idx: u32,
    /// The non-stalled player (the claimant).
    claimant_id: [u8; 20],
    /// The withheld commit head (zeros for shape 2).
    committed_head: [u8; 32],
    /// 1 = shape 1 (committed-withheld), 0 = shape 2 (never-committed).
    has_commit: u8,
}

/// Build the shape-2 forfeit-evidence wire manually (mirrors CR Task 3's decode
/// test): `turn_count(u16 LE) ‖ [tape_len(u16 LE)‖tape]×N ‖ head_k(32) ‖
/// sig_a(65) ‖ sig_b(65) ‖ shape(2)`.
fn build_forfeit_evidence_shape2(
    tapes: &[&[u8]],
    head_k: &[u8; 32],
    sig_a: &[u8],
    sig_b: &[u8],
) -> Vec<u8> {
    let mut b = Vec::new();
    b.extend_from_slice(&(tapes.len() as u16).to_le_bytes());
    for t in tapes {
        b.extend_from_slice(&(t.len() as u16).to_le_bytes());
        b.extend_from_slice(t);
    }
    b.extend_from_slice(head_k);
    b.extend_from_slice(sig_a);
    b.extend_from_slice(sig_b);
    b.push(2u8); // shape 2 (never-committed)
    b
}

/// Build the tag-3 witness lock: `tag(1) ‖ nonce0 ‖ nonce1 ‖ evidence_body`.
fn forfeit_witness(n0: &[u8; 32], n1: &[u8; 32], evidence_body: &[u8]) -> Vec<u8> {
    let mut w = Vec::with_capacity(1 + 64 + evidence_body.len());
    w.push(3u8); // tag = 3 (forfeit-claim)
    w.extend_from_slice(n0);
    w.extend_from_slice(n1);
    w.extend_from_slice(evidence_body);
    w
}

/// Build a forfeit-claim scenario from the first `n` tapes of the court fixture.
/// Folds the mutually-signed head `head_k` over the prefix, signs it with `key_a`
/// + `key_b`, and emits a shape-2 evidence body. The stalled player is attributed
/// by `team-of-turn = n % 2`; the claimant is the other player.
fn forfeit_claim_setup_keys(n: usize, key_a: &SigningKey, key_b: &SigningKey) -> ForfeitSetup {
    let (p0, p1) = player_ids();
    let (n0, n1) = nonces();
    let c0 = verifier::ckbhash(&n0);
    let c1 = verifier::ckbhash(&n1);
    let seed = derive_seed(&n0, &n1);
    assert_eq!(seed, 1234, "nonces must derive the fixture seed");
    let env = court_envelope();
    let e = decode_court_envelope(&env).expect("decode court envelope");
    assert!(e.tapes.len() >= n, "fixture must have at least {n} tapes");

    // Fold the chain head over the prefix (the value both players co-sign).
    let mut head = court_chain_genesis(seed);
    for (i, tape) in e.tapes[..n].iter().enumerate() {
        head = court_chain_step(&head, i as u32, tape);
    }
    let head_k = head;
    let sig_a = sign_recoverable(key_a, &head_k);
    let sig_b = sign_recoverable(key_b, &head_k);
    let evidence_body = build_forfeit_evidence_shape2(&e.tapes[..n], &head_k, &sig_a, &sig_b);

    // team-of-turn = idx % 2; stalled = that team's player, claimant = the other.
    let stalled_idx = n as u32;
    let claimant_id = if (stalled_idx % 2) == 0 { p1 } else { p0 };

    let args = build_args(&p0, &p1, &c0, &c1);
    let witness_lock = forfeit_witness(&n0, &n1, &evidence_body);
    ForfeitSetup {
        args,
        witness_lock,
        head_k,
        stalled_idx,
        claimant_id,
        committed_head: [0u8; 32],
        has_commit: 0,
    }
}

/// Canonical valid shape-2 forfeit-claim setup: the first 5 tapes of the fixture
/// (match still in progress), mutually signed by both player keys.
fn forfeit_claim_setup() -> ForfeitSetup {
    let (k0, k1) = signing_keys();
    let setup = forfeit_claim_setup_keys(5, &k0, &k1);
    // Sanity: the 5-tape prefix is mid-match (no winner yet) — a finished match
    // settles via the court path, not forfeit.
    let (n0, n1) = nonces();
    let seed = derive_seed(&n0, &n1);
    let env = court_envelope();
    let e = decode_court_envelope(&env).expect("decode court envelope");
    let mut w = create_world(seed, 1280, 720);
    for tape in &e.tapes[..5] {
        for input in decode_tape(tape) {
            step_world(&mut w, &input);
        }
    }
    assert!(w.winner.is_none(), "5-tape prefix must be mid-match");
    setup
}

/// Assemble + verify a Path-3 (forfeit-claim) spend. Deploys the escrow binary,
/// builds the escrow script from `setup.args`, creates the POT input with the
/// given absolute-block `since`, and ONE output = the pending-forfeit cell whose
/// lock is the pinned forfeit-lock and whose args are the expected 316-byte blob
/// (layout B), capacity POT. `output_code_hash_override` swaps the output lock's
/// code_hash (to prove the forfeit-pin rejection).
fn run_forfeit_claim(
    setup: &ForfeitSetup,
    since: u64,
    output_code_hash_override: Option<[u8; 32]>,
) -> Result<u64, ckb_testtool::ckb_error::Error> {
    let mut ctx = Context::default();
    let bin: Bytes = std::fs::read(ESCROW_BIN)
        .expect("escrow-lock binary missing — build it for riscv64imac-unknown-none-elf first")
        .into();
    let escrow_out = ctx.deploy_cell(bin);
    let lock = ctx
        .build_script(&escrow_out, Bytes::from(setup.args.clone()))
        .expect("build escrow lock");

    // The escrow-lock's OWN identity, exactly as the contract reads via load_script().
    let escrow_code_hash: [u8; 32] = lock.code_hash().as_slice().try_into().unwrap();
    let escrow_hash_type: u8 = lock.hash_type().into();

    // forfeit_deadline = claim_since + reveal_window (reveal_window pinned in args).
    let forfeit_deadline = since + REVEAL_WINDOW;

    // Build the expected 316-byte pending-forfeit args blob (layout B).
    let mut blob = Vec::with_capacity(316);
    blob.extend_from_slice(&escrow_code_hash); // [0..32]    escrow code_hash (PIN)
    blob.push(escrow_hash_type); // [32]       escrow hash_type
    blob.extend_from_slice(&setup.args); // [33..219]  escrow args VERBATIM (186)
    blob.extend_from_slice(&setup.claimant_id); // [219..239] claimant_id (20)
    blob.extend_from_slice(&setup.stalled_idx.to_le_bytes()); // [239..243] stalled_idx (4 LE)
    blob.extend_from_slice(&setup.head_k); // [243..275] head_k (32)
    blob.extend_from_slice(&setup.committed_head); // [275..307] committed_head (32)
    blob.push(setup.has_commit); // [307]      has_commit (1)
    blob.extend_from_slice(&forfeit_deadline.to_le_bytes()); // [308..316] deadline (8 LE)
    assert_eq!(blob.len(), 316, "pending-forfeit args must be 316 bytes");

    // The pending-forfeit output lock: pinned forfeit-lock identity + expected blob.
    let (forfeit_code_hash, _) = forfeit_lock_identity();
    let out_code_hash = output_code_hash_override.unwrap_or(forfeit_code_hash);
    let forfeit_lock = Script::new_builder()
        .code_hash(out_code_hash.pack())
        .hash_type(ScriptHashType::Data1)
        .args(Bytes::from(blob).pack())
        .build();

    let input_cell = ctx.create_cell(
        CellOutput::new_builder().capacity(POT).lock(lock).build(),
        Bytes::new(),
    );
    // Absolute-block-number since: top byte 0, value = block height.
    let since_packed: Uint64 = since.pack();
    let input = CellInput::new_builder()
        .since(since_packed)
        .previous_output(input_cell)
        .build();
    let witness = WitnessArgs::new_builder()
        .lock(Some(Bytes::from(setup.witness_lock.clone())).pack())
        .build();

    let tb = TransactionBuilder::default()
        .input(input)
        .witness(witness.as_bytes().pack())
        .output(
            CellOutput::new_builder()
                .capacity(POT)
                .lock(forfeit_lock)
                .build(),
        )
        .output_data(Bytes::new().pack());
    let tx = ctx.complete_tx(tb.build());
    ctx.verify_tx(&tx, 200_000_000).map(|c| c as u64)
}

#[test]
fn accepts_forfeit_claim_shape2() {
    let setup = forfeit_claim_setup();
    let r = run_forfeit_claim(&setup, 500, None);
    assert!(
        r.is_ok(),
        "valid shape-2 forfeit-claim must unlock, got {:?}",
        r.err()
    );
    if let Ok(cycles) = r {
        eprintln!("forfeit-claim shape2 cycles: {cycles}");
    }
}

#[test]
fn rejects_forfeit_forged_prefix() {
    let mut setup = forfeit_claim_setup();
    // Flip one byte of the first prefix tape so the replay head != posted head_k.
    // evidence_body starts at witness offset 65 (tag‖nonce0‖nonce1); within it,
    // turn_count(2) + first tape_len(2) → first tape byte at 65 + 4.
    setup.witness_lock[65 + 4] ^= 0x01;
    let r = run_forfeit_claim(&setup, 500, None);
    assert!(
        r.is_err(),
        "a forged prefix tape must reject (replay head != posted head_k, E_FORFEIT_PREFIX)"
    );
}

#[test]
fn rejects_forfeit_bad_mutual_sig() {
    let (k0, _k1) = signing_keys();
    // Both sigs from k0 → they recover to {p0, p0}, which does not cover {p0, p1}.
    let setup = forfeit_claim_setup_keys(5, &k0, &k0);
    let r = run_forfeit_claim(&setup, 500, None);
    assert!(
        r.is_err(),
        "mutual sigs not covering {{p0,p1}} must reject (E_FORFEIT_MUTUAL)"
    );
}

#[test]
fn rejects_forfeit_match_already_over() {
    let (k0, k1) = signing_keys();
    // Use the FULL 23-tape fixture as the prefix → the replay sets a winner, so
    // the match is over and must settle via the court path, not forfeit.
    let setup = forfeit_claim_setup_keys(23, &k0, &k1);
    let r = run_forfeit_claim(&setup, 500, None);
    assert!(
        r.is_err(),
        "a prefix that already finished the match must reject (E_FORFEIT_MATCH_OVER)"
    );
    // A rejected script exposes no cycle count via verify_tx; the rejection lands
    // only AFTER the full 23-tape replay (check 5 follows the check-4 replay).
    match r {
        Ok(cycles) => eprintln!("forfeit match-over cycles: {cycles}"),
        Err(e) => eprintln!("forfeit match-over rejected after full replay: {e}"),
    }
}

#[test]
fn rejects_forfeit_output_wrong_lock() {
    let setup = forfeit_claim_setup();
    // Pending-forfeit output under an attacker code_hash (not the pinned forfeit-lock).
    let r = run_forfeit_claim(&setup, 500, Some([0xFFu8; 32]));
    assert!(
        r.is_err(),
        "pending-forfeit output under an attacker lock must reject (E_FORFEIT_OUTPUT)"
    );
}

// RESIDUAL — final-move equivocation (see ESCROW.md §8 / design spec §6). The
// court fixture IS the loser-final-actor (self-destruct) shape: 23 turns, team0
// acts last on turn 22 (even index), winner=1 (see fixture-court.meta.txt).
// Player1's final-head signature covers only up to player1's last turn (turn 21)
// and does NOT cover the final move (turn 22, player0's). This is exactly
// sub-case B of the exploit — played honestly (team0's real final move
// self-destructs, team1 wins legitimately).
//
// THE RESIDUAL: player0 (loser, final actor) could re-sign a forged winning or
// drawing final move using their own key and submit it to the court. The court
// has NO challenge window — it is first-valid-spend-wins (a RACE). An honest
// winner's worst case is TOTAL LOSS: a winning forge takes 100% of the pot; a
// drawing forge forces a 50/50 split. The refund path (tag 2, deadline split)
// does NOT bound an active forger — it only protects against inaction.
//
// A reproducing exploit test (constructing a forged winning final move) and the
// challenge-window fix are deferred to the follow-up. Tracked in ESCROW.md §8 /
// design spec §6.
