#!/usr/bin/env python3
"""Generate `src/tape_demo_data.rs` from the canonical demo tape.

The no_std CKB-VM bench cannot parse JSON, so the demo tape is pre-flattened
into a Rust source array embedded at compile time. Regenerate after the tape
or its golden hash changes:

    python3 verifier/bench/gen-tape.py

Reads  : ../tests/tape-demo.json  (seed + per-tick inputs)
         ../tests/tape-demo.hash  (0x-prefixed blake2b-256 golden commitment)
Writes : src/tape_demo_data.rs    (committed; the bench includes it as a module)

Input encoding: each tick is a tuple
    (aim_up, aim_down, aim_left, aim_right, fire_held, fire_pressed,
     fire_released, select_weapon)
where the seven flags are `bool` and `select_weapon` is `i32` with the sentinel
`-1` meaning `None` (no weapon selected this tick). The bench maps `-1 -> None`
and `n >= 0 -> Some(n)` when building each `TickInput`.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
JSON = os.path.join(HERE, "..", "tests", "tape-demo.json")
HASH = os.path.join(HERE, "..", "tests", "tape-demo.hash")
OUT = os.path.join(HERE, "src", "tape_demo_data.rs")


def b(v):
    return "true" if v else "false"


def main():
    with open(JSON) as f:
        tape = json.load(f)
    seed = int(tape["seed"])
    inputs = tape["inputs"]

    golden_hex = open(HASH).read().strip()
    assert golden_hex.startswith("0x") and len(golden_hex) == 66, golden_hex
    raw = bytes.fromhex(golden_hex[2:])
    golden_bytes = ", ".join(f"0x{x:02x}" for x in raw)

    rows = []
    for inp in inputs:
        sw = inp.get("selectWeapon")
        sw = -1 if sw is None else int(sw)
        rows.append(
            "    ({}, {}, {}, {}, {}, {}, {}, {}),".format(
                b(inp.get("aimUp")),
                b(inp.get("aimDown")),
                b(inp.get("aimLeft")),
                b(inp.get("aimRight")),
                b(inp.get("fireHeld")),
                b(inp.get("firePressed")),
                b(inp.get("fireReleased")),
                sw,
            )
        )

    body = "\n".join(rows)
    n = len(inputs)
    out = f"""//! GENERATED by `verifier/bench/gen-tape.py` from `tests/tape-demo.json` +
//! `tests/tape-demo.hash`. DO NOT EDIT BY HAND — rerun the generator instead.
//!
//! Flattened demo tape embedded into the no_std CKB-VM full-replay bench.
//! Each `INPUTS` row is one tick:
//!   (aim_up, aim_down, aim_left, aim_right, fire_held, fire_pressed,
//!    fire_released, select_weapon)
//! `select_weapon == -1` means `None`; `>= 0` means `Some(n)`.

/// World seed for `create_world(SEED, 1280, 720)`.
pub const SEED: i32 = {seed};

/// blake2b-256 (`ckb-default-hash`) of the committed world after replaying all
/// {n} ticks — the self-gate the bench exits 0 on.
pub const GOLDEN: [u8; 32] = [{golden_bytes}];

/// {n} per-tick inputs, in replay order.
pub static INPUTS: &[(bool, bool, bool, bool, bool, bool, bool, i32)] = &[
{body}
];
"""
    with open(OUT, "w") as f:
        f.write(out)
    print(f"wrote {OUT}: seed={seed}, {len(inputs)} ticks, golden={golden_hex}")


if __name__ == "__main__":
    main()
